# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_devices', '0003_node_last_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 8, 52, 41, 345721, tzinfo=utc)),
        ),
    ]
