# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_devices', '0004_auto_20171121_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 14, 50, 39, 437414, tzinfo=utc)),
        ),
    ]
