# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_devices', '0005_auto_20171121_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 9, 9, 13, 938460, tzinfo=utc)),
        ),
    ]
