# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 06:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_devices', '0006_auto_20171207_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 6, 12, 14, 363150, tzinfo=utc)),
        ),
    ]
