# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_devices', '0014_auto_20171221_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Area'),
        ),
        migrations.AlterField(
            model_name='node',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 14, 13, 17, 21, 785051, tzinfo=utc)),
        ),
    ]
