# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:05
from __future__ import unicode_literals

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, default='new', max_length=20)),
                ('publication_date', models.DateField(blank=True)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('number_of_pages', models.PositiveIntegerField(blank=True)),
                ('format', models.CharField(blank=True, max_length=50)),
                ('inventory', models.PositiveIntegerField(blank=True)),
                ('image', models.ImageField(max_length=500, upload_to=books.models.upload_image_to)),
                ('archive_link', models.FileField(editable=False, max_length=500, null=True, upload_to=None)),
                ('authors', models.ManyToManyField(blank=True, to='books.Author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, to='books.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Publisher'),
        ),
    ]
