# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.FloatField()),
                ('oxi', models.FloatField()),
                ('measuring_date', models.DateField(default=datetime.date(2017, 9, 15))),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuring_date', models.DateTimeField(auto_created=True)),
                ('co', models.FloatField()),
                ('oxi', models.FloatField()),
                ('node_name', models.CharField(max_length=255)),
            ],
        ),
    ]
