# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_devices', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_devices.Node'),
        ),
        migrations.AddField(
            model_name='data',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Area'),
        ),
    ]
