# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170915_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='measuring_date',
            field=models.DateField(default=datetime.date(2017, 9, 17)),
        ),
    ]
