# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 03:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170917_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='measuring_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 18, 3, 56, 2, 705549, tzinfo=utc)),
        ),
    ]
