# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 06:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20171207_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdata',
            old_name='node_name',
            new_name='node_identification',
        ),
        migrations.AlterField(
            model_name='aqi',
            name='of_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 15, 6, 12, 14, 372151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='measuring_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 15, 6, 12, 14, 370150, tzinfo=utc)),
        ),
    ]
