# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 11:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20171215_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqi',
            name='forecast',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aqi',
            name='of_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 18, 11, 10, 51, 949358, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='measuring_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 18, 11, 10, 51, 947358, tzinfo=utc)),
        ),
    ]
