# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20171221_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqi',
            name='of_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 14, 13, 17, 21, 792051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='measuring_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 14, 13, 17, 21, 790051, tzinfo=utc)),
        ),
    ]
