# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Default location', max_length=120),
        ),
    ]
